wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 32
EARLY_STOPPING_PATIENCE:
  desc: null
  value: 10
EPOCHS:
  desc: null
  value: 30
INPUT_SHAPE:
  desc: null
  value: 128
LEARNING_RATE:
  desc: null
  value: 0.0005
_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1644547864
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 16
      4: 3.8.5
      5: 0.12.10
      8:
      - 1
      - 5
